Homework 2
azatnv/RecoServiceTemplate pull request #4
Opened 2022-11-26 12:37 UTC by azatnv

2022-11-26 17:10 UTC, sharthZ23 requested changes
- По `UsersKFoldPout` все ок
- По `pFound` - надо обернуть в функции и сравнивать скорость работы
- По `MRR` - график неподходящий, по нему ничего не видно, придумайте получше что-то

2022-11-28 20:51 UTC, ArtDread commented
> * По `pFound` - надо обернуть в функции и сравнивать скорость работы
✅ Check
> * По `MRR` - график неподходящий, по нему ничего не видно, придумайте получше что-то
✅ Check

2022-11-29 06:59 UTC, smeyanoff commented
На github не отображаются графики. 

![image](https://user-images.githubusercontent.com/108741347/204459874-34c071d2-9237-477a-954b-8e7651f5ef07.png)
![image](https://user-images.githubusercontent.com/108741347/204459967-8cb72539-6fb5-4475-9595-7ff90bd0352d.png)

2022-12-01 20:08 UTC, sharthZ23 approved these changes
Принимаю, 22 балла поставлю за дз. За что минус баллы:
- Не сравнения корректности функций подсчета MRR
- Графики из plotly легко сохранить, но можно было просто matplotlib/seaborn использовать перед публикацией на github например

2022-12-01 20:08 UTC, merged