Homework 3
azatnv/RecoServiceTemplate pull request #8
Opened 2022-12-10 13:00 UTC by azatnv

2022-12-10 20:46 UTC, sharthZ23 requested changes
У меня следующие вопросы:
- Где загрузка моделей из конфига?
- Где генерация рекомендаций по запросу, то есть сам ответ на запрос?
- Где анализ скорости ответов у онлайн модели?
- Вы прогоняли сверху вниз свои ipynb перед публикацией? Там есть куча логических пропусков

2022-12-11 13:17 UTC, azatnv commented
Исправил [hw_3_userknn.ipynb](https://github.com/azatnv/RecoServiceTemplate/blob/develop/notebooks/hw_3_userknn.ipynb). Код воспроизводится, заполнены логические пропуски, добавлен анализ скорости ответов у онлайн модели

2022-12-11 21:25 UTC, azatnv commented
Добавили файл ```configuration.py```, содержащий пути к бинарным файлам моделей:
https://github.com/azatnv/RecoServiceTemplate/blob/e07fda53d3b20d4e11a3e39bb6b2c2365962e194/config/configuration.py#L1-L6
Используем их для инициализации моделей:
https://github.com/azatnv/RecoServiceTemplate/blob/e07fda53d3b20d4e11a3e39bb6b2c2365962e194/service/api/views.py#L8-L13
https://github.com/azatnv/RecoServiceTemplate/blob/e07fda53d3b20d4e11a3e39bb6b2c2365962e194/service/api/views.py#L25-L36

2022-12-12 09:54 UTC, sharthZ23 approved these changes
Готов 24 балла поставить. На 25 поправьте последний комментарий

2022-12-12 09:54 UTC, sharthZ23 commented on service/api/views.py
> +        raise ModelNotFoundError(error_message=f"Model {model_name} not found")
Кажется тут Response должен быть такой, что модель не найдена, а не exception

2022-12-12 10:38 UTC, azatnv commented on service/api/views.py
> +        raise ModelNotFoundError(error_message=f"Model {model_name} not found")
Мы ведь отлавливаем это исключение и возвращаем HTTPStatus.NOT_FOUND с сообщением "Model {model_name} not found".

![image](https://user-images.githubusercontent.com/31849841/207024390-e9f100e0-27c4-47ec-8460-a776a2ef2876.png)

2022-12-12 10:43 UTC, azatnv commented on service/api/views.py
> +        raise ModelNotFoundError(error_message=f"Model {model_name} not found")
Даже написали тест на такой случай:

https://github.com/azatnv/RecoServiceTemplate/blob/e07fda53d3b20d4e11a3e39bb6b2c2365962e194/tests/api/test_views.py#L44-L56

2022-12-12 10:45 UTC, sharthZ23 commented on service/api/views.py
> +        raise ModelNotFoundError(error_message=f"Model {model_name} not found")
Понял, проглядел я. Тогда принято, 25 баллов, мерджите ветку

2022-12-14 21:22 UTC, merged